config/routes.rb
Rails.application.routes.draw do
  resources :v_space
  devise_for :users
  resources :products do
    resources :orders, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'seller' => "products#seller"
  get 'search' => "products#search", :as => 'search_page'
  get 'products/:id', to: 'products#show', as: 'show_product'
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  root to: 'v_space#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    validates :address, :city, :state, presence: true

    belongs_to :product
    belongs_to :buyer, class_name: "User"
    belongs_to :seller, class_name: "User"
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image

    validates :name, :description, :price, presence: true
    validates :price, numericality: { greater_than: 0 }

    belongs_to :user
    has_many :orders
    
    paginates_per 8
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

    validates :name, presence: true
    has_many :products, dependent: :destroy
    has_many :sales, class_name: "Order", foreign_key: "seller_id"
    has_many :purchases, class_name: "Order", foreign_key: "buyer_id"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  # Error Page
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # sales history page
  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end
  # purchases history page
  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  # GET /orders/new
  def new
    @order = Order.new
    @product = Product.find(params[:product_id])
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    @product = Product.find(params[:product_id])
    @seller = @product.user

    @order.product_id = @product.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to products_url, notice: "Order was successfully." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  
  # GET /products or /products.json
  def index
    @products = Product.page(params[:page]).order("created_at DESC")
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /serach
  def search  
    if params[:search].blank?  
      redirect_to(products_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase  
      @results = Product.all.where("lower(name) LIKE :search", search: "%#{@parameter}%" )
    end
  end

  # Manage Product Page
  def seller
      @products = Product.where(user: current_user).order("created_at DESC")
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def set_product
  @product = Product.find(params[:id])
  end

  def product_params
  params.require(:product).permit(:name, :description, :price, :image, :search)
  end

  def check_user
  if current_user == "product.user"
      redirect_to root_url, alert: "Sorry, this product belongs to someone else"
  end
  end

end

app/controllers/v_space_controller.rb
class VSpaceController < ApplicationController
    # Root page or Index [v_space#index]
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/v_space_helper.rb
module VSpaceHelper
end

app/views/layouts/_footer.html.erb
<%# footer %>
<br>
<div class="container">
<p>Copyright by Anon 2021</p>
</div>

app/views/layouts/_header.html.erb
<%# header & nav bar %>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
    <ul class="navbar-nav mr-auto">
    <a class="navbar-brand-auto">
    <%= link_to root_path do %>
    <img src="https://res.cloudinary.com/ddqegwuzs/image/upload/v1621580383/Vspace_gfo16b.png" alt="" width="40" height="40">
    <% end %>
    </a>
        <li class="navbar-brand mb-0 h1">
        <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="navbar-brand mb-0 h1">
        <%= link_to "Product", products_path, class: "nav-link" %>
        </li>
    </ul>

        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="nav-item dropdown mb-0 h5">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Manage </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><%= link_to "Manage Product", seller_path, class: "nav-link" %></li>
            <li><%= link_to "Sales History", sales_path, class: "nav-link" %></li>
            <li><%= link_to "Purchase History", purchases_path, class: "nav-link" %></li>
        </ul>
        </li>

        <li class="nav-item dropdown mb-0 h5">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, class: "nav-link", method: :delete %></li>
        </ul>
        </li>
        <% else %>
            <li class="mb-0 h5"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
            <li class="mb-0 h5"><%= link_to "Sign In", new_user_session_path, class: "nav-link" %></li>
    <% end %>
    </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<%# main layout app %>
<!DOCTYPE html>
<html>
  <head>
    <title>VSpace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    
    <div class="container">
      <p>
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissable">
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
      </p>
    <%= yield %>

    <%= render 'layouts/footer' %>
  </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%# form for display on the order page %>

<div class="container-fluid">
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <% if @product.image.attached? %>
      <%= image_tag @product.image, crop: :scale, width: "80%" %>
      <% else %>
      <img src="https://res.cloudinary.com/ddqegwuzs/image/upload/v1622048177/noimage_pzxizf.gif" alt="" width="80%">
      <% end %>
    </div>
    <p><h3><%= @product.name %></h3></p>
    <h5><%= number_to_currency(@product.price) %></h5>
  </div>
  <div class="col-md-8">
<%= form_for([@product, @order]) do |f| %>
  <% if order.errors.any? %>
      <div class="alert alert-danger alert-dismissable">
      <div id="error_explanation">
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>
      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    </div>
  <% end %>

<h5>Address Information</h5>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: "form-control" %>
  </div>
<br>
  <h5>Payment Information</h5>
  <div class="form-group">
    <div class="row">
    <label for="validationDefault03" class="form-label">Card Holder's Name</label>
      <div class="col-md-10">  
        <input type="text" class="form-control" pattern="\w+ \w+.*" required required>
      </div>
      </div>
      <label for="validationDefault03" class="form-label">Credit Card Number</label>
        <div class="input-group md-3">
          <div class="input-group-number">
            <input type="text" class="input-block-level" autocomplete="off" maxlength="4" pattern="\d{4}" required>
          &nbsp
            <input type="text" class="input-block-level" autocomplete="off" maxlength="4" pattern="\d{4}" required>
          &nbsp
            <input type="text" class="input-block-level" autocomplete="off" maxlength="4" pattern="\d{4}" required>
          &nbsp
            <input type="text" class="input-block-level" autocomplete="off" maxlength="4" pattern="\d{4}" required>
        </div>
      </div>
      <label for="validationDefault03" class="form-label">CVV</label>
        <div class="input-group md-3">
          <div class="input-group-number">
            <input type="text" class="input-block-level" autocomplete="off" maxlength="3" pattern="\d{3}" required>
        </div>
      </div>
  </div>


  <div class="form-group">
    <%= label_tag nil, "Expiration Date" %>
    <div class="row">
      <div class="col-md-3">
        <p><%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'nil' => "exp-month", class: "form-control" } %></p>
      </div>
      <div class="col-md-3">
        <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+20 }, { :name => nil, :'nil' => "exp-year", class: "form-control" } %>
      </div>
    </div>

  <br>
  <div class="form-group">
    <p><%= f.submit "Order", class: "btn btn-primary" %></p>
  </div>
<% end %>
</div>
</div>

app/views/orders/new.html.erb
<%# the order page %>

<%= render 'form', order: @order %>
<br>
<div class="d-grid gap-2">
<%= link_to 'Back', product_path(@product), class: "btn btn-outline-warning" %>
</div>

app/views/orders/purchases.html.erb
<%# Purchase History Page %>

<div class="center">
    <h2>Purchase History</h2>
</div>

    <div class="table-responsive">
    <table class="table table-striped table-hover">
    <tr>
        <th class="center">Image</th>
        <th class="center">Product</th>
        <th class="center">Price</th>
        <th class="center">Customer</th>
        <th class="center">Date Purchased</th>
    </tr>

    <% @orders.each do |order| %>
        <tr>
        <td class="center">
        <% if order.product.image.url %>
            <img src= <%= order.product.image.url %> width="40%">
            <% else %>
            <img src="https://res.cloudinary.com/ddqegwuzs/image/upload/v1622048177/noimage_pzxizf.gif" alt="" width="40%">
        <% end %>
        </td>
        <td class="center"><%= order.product.name %></td>
        <td class="center"><%= number_to_currency(order.product.price) %></td>
        <td class="center"><%= order.seller.name %></td>
        <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
    <% end %>
    </table>
    </div>
<br>
<div class="d-grid gap-2">
<%= link_to 'Back', products_path, class: "btn btn-outline-warning" %>
</div>
<br>

app/views/orders/sales.html.erb
<%# Sales History Page %>

<div class="center">
    <h2>Sales History</h2>
</div>

    <div class="table-responsive">
    <table class="table table-striped table-hover">
    <tr>
        <th class="center">Image</th>
        <th class="center">Product</th>
        <th class="center">Price</th>
        <th class="center">Customer</th>
        <th class="center">Date Sold</th>
    </tr>

    <% @orders.each do |order| %>
        <tr>
        <td class="center">
        <% if order.product.image.url %>
            <img src= <%= order.product.image.url %> width="40%">
            <% else %>
            <img src="https://res.cloudinary.com/ddqegwuzs/image/upload/v1622048177/noimage_pzxizf.gif" alt="" width="40%">
        <% end %>
        </td>
        <td class="center"><%= order.product.name %></td>
        <td class="center"><%= number_to_currency(order.product.price) %></td>
        <td class="center"><%= order.buyer.name %></td>
        <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
        </tr>
    <% end %>
    </table>
    </div>
<br>
<div class="d-grid gap-2">
<%= link_to 'Back', products_path, class: "btn btn-outline-warning" %>
</div>
<br>

app/views/products/_body.html.erb
<%# form of products page %>

<p>
<div class="center">
<div class="row">
<% @products.each do |product| %>
    <% if product.image.url %>
        <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="card">
        <div class="card-header">
        Product
        </div>
            <div class="card-body">
            <img src= <%= product.image.url %> width="100%">
            </p>
                <h3><%= product.name %></h3>
                <p><%= number_to_currency (product.price) %></p>
                <p><%= "By #{product.user.name}" %></p>
                <%= link_to 'Detail', product, class: "btn btn-primary" %>
            </div>
        </div>
        </div>
    <% end %>
<% end %>
</div>
</div>
<br>
    <%= paginate @products %>
<br>

<% if user_signed_in? %>
    <%= link_to 'New Product', new_product_path, class: "btn btn-success" %>
<% end %>

app/views/products/_bodymanage.html.erb
<%# form of manage page %>

<br>
<div class="center">
<div class="row">
<% @products.each do |product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="card">
    <div class="card-header">
    Product
    </div>
        <div class="card-body">
        <% if product.image.url %>
        <img src= <%= product.image.url %> width="100%">
        <% else %>
        <img src="https://res.cloudinary.com/ddqegwuzs/image/upload/v1622048177/noimage_pzxizf.gif" alt="" width="70%">
        <% end %>
        </p>
            <h3><%= product.name %></h3>
            <p><%= product.description %></p>
            <p><%= number_to_currency (product.price) %></p>
                <%= link_to 'Edit', edit_product_path(product), class: "btn btn-warning" %>
                <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div>
    </div>
    </div>
<% end %>
</div>
</div>
<br>
<%= link_to 'New Product', new_product_path, class: "btn btn-success" %>
<%= link_to 'Back', products_path, class: "btn btn-outline-warning" %>

app/views/products/_form.html.erb
<%# product form %>

<%= form_for([@product]) do |f| %>
  <% if product.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <div id="error_explanation">
      <h4><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h4>
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>
<p>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
</p>
<p>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
</p>
<p>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
</p>
<p>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
</p>
<p>
  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
</p>
<% end %>

app/views/products/_header.html.erb
<%# search bar %>
<br>
<%= form_tag(search_page_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
    <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
    <%= button_tag "Go", :class => 'btn btn-secondary',:name => nil%>  
    </div>  
</div>  
<% end %>
<br>

app/views/products/edit.html.erb
<% if current_user == @product.user %>
    <h1>Editing Product</h1>
    <%= render 'form', product: @product %>
    <%= link_to 'Manage', seller_path, class: "btn btn-secondary" %>
    <% else %>
        <p><img src="https://res.cloudinary.com/ddqegwuzs/image/upload/v1622047963/error404_ccgf49.gif" alt="" width="100%"></p>
<% end %>
<p></p>
<p><%= link_to 'Back', products_path, class: "btn btn-outline-warning" %></p>

app/views/products/index.html.erb
<%= render 'header' %>

<h1>Products</h1>

<%= render 'body' %>

<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class: "btn btn-outline-warning" %>

app/views/products/search.html.erb
<h1>Search Results</h1>
    <% @results.each do |result| %>  
        <p><%= link_to result.name, show_product_path(result) %></p>
    <% end %>
<%= link_to 'Back', products_path, class: "btn btn-outline-warning" %>

<br>

app/views/products/seller.html.erb
<h1>Manage Product</h1>

<%= render 'bodymanage' %>

app/views/products/show.html.erb
<div class="container-fluid">
<div class="row">
  <div class="col-md-6">
    <div class="card-body">
          <% if @product.image.attached? %>
          <%= image_tag @product.image, crop: :scale, width: "100%" %>
          <% else %>
          <img src="https://res.cloudinary.com/ddqegwuzs/image/upload/v1622048177/noimage_pzxizf.gif" alt="" width="100%">
          <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card-body">
    <h3><%= @product.name %></h3>
    <p><%= "By #{@product.user.name}" %></p>
    <p><%= number_to_currency (@product.price) %></p>
    <p><%= @product.description %></p>
    <br>
    <% if current_user == @product.user %>
    <% else %>
      <% if @product.image.attached? %>
          <div class="left">
            <%= link_to "Buy This Product", new_product_order_path(@product), class: "btn btn-primary" %>
        <% else %>
          <h5 style="color:red">The product is not available for purchase.</h5>
      <% end %>
    <% end %>
    </div>
    </div>
  </div>
</div>
<br>
<div class="d-grid gap-2">
<% if current_user == @product.user %>
  <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-secondary" %>
<% end %>
  <%= link_to 'Back', products_path, class: "btn btn-outline-warning" %>
</div>

app/views/v_space/_form.html.erb
<%# form index page %>
<div class="card bg-dark text-white">
    <img src="https://res.cloudinary.com/ddqegwuzs/image/upload/v1622047360/home_acy4no.gif" class="card-img" alt="...">
        <div class="card-img-overlay">
        <h1 class="card-title">Hello Designer</h1>
    </div>
    <div class="card-body">
        <h3 class="card-title">Enjoy with us !!</h3>
        <p class="card-text">Digital art online marketplace that serves users to deals with their own works freely.</p>
        <p class="card-text">Find the product on the product page or click the link below.</p>
        <h4 class="text" style="font-size: 2vw; line-height: 1px; color: white; position: relative;">
        <%= link_to "Product", '/products', class: "btn btn-outline-light" %>
        </h4>
    </div>
</div>

app/views/v_space/index.html.erb
<%# view of root page or index %>
<p></p>
<h1>Welcome to V-Space</h1>
<h2>Digital Art Online Marketplace</h2>
<%= render 'form' %>